name: ardrive_network
description: ArDrive Network abstractions
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: 3.0.5

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  isolate_manager: ^2.0.1+3
  isolated_worker: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
