name: '[PR][IOS] Build and Deploy'
on:
  pull_request:
    branches-ignore:
      - gh-pages
      - master
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install FLutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Set FIREBASE_JSON env var
        run: |
          echo "FIREBASE_JSON=$RUNNER_TEMP/firebase.json" >> $GITHUB_ENV

      - name: Save Firebase Service Account json
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: |
          echo -n "$FIREBASE_SERVICE_ACCOUNT_JSON" >> $FIREBASE_JSON

      - name: Build iOS with fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.FASTLANE_SSH_KEY }}
          BUILD_NUMBER: ${{ github.run_id }}
          RELEASE_NOTES: ${{ github.event.pull_request.title }} - ${{ github.sha }}
        run: |
          cd ios && fastlane adhoc
