name: Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      # Set Flutter version from fvm
      - uses: kuhnroyal/flutter-fvm-config-action@v1

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install script_runner
        run: flutter pub global activate script_runner

      - name: Build app
        run: scr setup

      - name: Test app
        run: scr test
