name: 'Staging deploy'

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

env:
  BUILD_NUMBER: ${{ github.run_number }}
  RELEASE_NOTES: Staging - ${{ github.sha }}
  FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Build app
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Test
        run: |
          flutter test

  web:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Build app
        run: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter config --enable-web
          flutter build web --release

      # JS files cache invalidation
      - name: main.dart.js cache invalidation
        run: |
          sed -i 's/main.dart.js/main.dart.js?version='"$GITHUB_SHA"'/' build/web/index.html

      # Deploy to github pages
      - uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/web
          clean: true

  ios:
    needs: test
    runs-on: macos-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Set FIREBASE_JSON env var
        run: |
          echo "FIREBASE_JSON=$RUNNER_TEMP/firebase.json" >> $GITHUB_ENV

      - name: Save Firebase Service Account json
        run: |
          echo -n "$FIREBASE_SERVICE_ACCOUNT_JSON" >> $FIREBASE_JSON

      - name: Install fastlane and Cocoapods
        working-directory: ./ios
        run: |
          bundle install

      - name: Build iOS with fastlane
        env:
          MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
          MATCH_GIT_PRIVATE_KEY: ${{ secrets.FASTLANE_SSH_KEY }}
        working-directory: ./ios
        run: |
          bundle exec fastlane deploy_adhoc

  android:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      # Install JDK
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Set FIREBASE_JSON env var
        run: |
          echo "FIREBASE_JSON=$RUNNER_TEMP/firebase.json" >> $GITHUB_ENV

      - name: Save Firebase Service Account json
        run: |
          echo -n "$FIREBASE_SERVICE_ACCOUNT_JSON" >> $FIREBASE_JSON

      - name: Install fastlane
        working-directory: ./android
        run: |
          bundle install

      - name: Build Android with fastlane
        working-directory: ./android
        run: |
          bundle exec fastlane deploy_apk
