on:
  workflow_call:

jobs:
  pr-title-check:
    uses: ./.github/workflows/pr_title_check.yaml
  
  setup:
    uses: ./.github/workflows/setup.yml

  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Lint
        run: flutter analyze

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Test app
        run: scr test
