on:
  workflow_call:

jobs:
  pr-title-check:
    uses: ./.github/workflows/pr_title_check.yaml

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true

      - name: Fetch dependencies
        run: flutter pub get

      - name: Lint
        run: flutter analyze

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Set Flutter version from fvm
      - uses: kuhnroyal/flutter-fvm-config-action@v1

      # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install script_runner
        run: flutter pub global activate script_runner

      - name: Build app
        run: scr setup

      - name: Test app
        run: scr test
