on:
  workflow_call:

jobs:
  pr-title-check:
    uses: ./.github/workflows/pr_title_check.yaml

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: ./.github/workflows/setup.yml

      - name: Lint
        run: flutter analyze

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Set Flutter version from fvm
      - uses: kuhnroyal/flutter-fvm-config-action@v1

      # Install Flutter
      - uses: ./.github/workflows/setup.yml

      - name: Test app
        run: scr test
