name: '[PR][WEB] Build and Deploy'
on:
  pull_request:
    branches-ignore:
      - gh-pages
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Build app
        run: |
          flutter pub get
          flutter pub run build_runner build
          flutter config --enable-web
          flutter build web --profile
      - name: main.dart.js cache invalidation
        run: |
          sed -i 's/main.dart.js/main.dart.js?version='"$GITHUB_SHA"'/' build/web/index.html
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_CI_SERVICE_ACCOUNT }}'
          expires: 14d
